# Generated by Django 3.0.1 on 2020-01-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=300)),
                ('project_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date analyzed')),
            ],
        ),
    ]
