# Generated by Django 3.0.1 on 2020-01-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='person_analysis',
            field=models.CharField(default='fanxuezhe', max_length=300),
            preserve_default=False,
        ),
    ]
