# Generated by Django 3.0.1 on 2020-01-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_record', '0002_history_person_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('person', models.CharField(max_length=20)),
                ('release_date', models.DateTimeField(verbose_name='date released')),
            ],
        ),
    ]
