# Generated by Django 3.0.1 on 2020-01-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_record', '0005_auto_20200120_0630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='project_namei',
        ),
        migrations.AddField(
            model_name='history',
            name='project_name',
            field=models.CharField(default='000000', max_length=20),
        ),
    ]
