# Generated by Django 3.0.1 on 2020-02-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_record', '0008_auto_20200120_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=40)),
                ('use_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='path_n',
            field=models.CharField(default='/home/fanxuezhe/files/', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateTimeField(blank=True, verbose_name='date released'),
        ),
    ]
